// <auto-generated />
using System;
using Laundry.Edge.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Laundry.Edge.Persistence.Migrations
{
    [DbContext(typeof(PlantDbContext))]
    [Migration("20260907185326_OutboxDeliveryTracking")]
    partial class OutboxDeliveryTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Laundry.Edge.Scans.LocalObservation", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_utc");

                    b.Property<string>("EventJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_json");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<string>("SubmissionJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("submission_json");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("EventId");

                    b.HasIndex("TenantId", "PlantId", "AcceptedAtUtc");

                    b.ToTable("observations", "plant");
                });

            modelBuilder.Entity("Laundry.Edge.Scans.OutboxEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("CloudReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cloud_received_at_utc");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<DateTimeOffset?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until_utc");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("EventId");

                    b.HasIndex("Status");

                    b.ToTable("outbox", "plant");
                });

            modelBuilder.Entity("Laundry.Edge.Scans.OutboxEntry", b =>
                {
                    b.HasOne("Laundry.Edge.Scans.LocalObservation", null)
                        .WithOne()
                        .HasForeignKey("Laundry.Edge.Scans.OutboxEntry", "EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
