// <auto-generated />
using System;
using Laundry.Api.Integrations.Scans;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Laundry.Api.Integrations.Scans.Migrations
{
    [DbContext(typeof(ScanDbContext))]
    partial class ScanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Laundry.Api.Integrations.Scans.ScanObservation", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("CloudReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cloud_received_at_utc");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("GatewayAcceptedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gateway_accepted_at_utc");

                    b.Property<string>("IdentifierTechnology")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identifier_technology");

                    b.Property<string>("IdentifierValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identifier_value");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("uuid")
                        .HasColumnName("plant_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid")
                        .HasColumnName("station_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("EventId")
                        .HasName("pk_scan_observations");

                    b.HasIndex("TenantId", "PlantId", "CloudReceivedAtUtc")
                        .HasDatabaseName("ix_scan_observations_tenant_plant_received");

                    b.ToTable("scan_observations", "integrations");
                });
#pragma warning restore 612, 618
        }
    }
}
